# cspell:words 0xMehedi Nurulya

name: "The Newcomer: Recruitment"
description: Player Recruitment Form
title: "[Player Tag]: "
labels:
  - newcomer
assignees:
  - 0xMehedi
body:
  - type: input
    id: profile-name
    attributes:
      label: Profile Name
      description: >
        Your Clash of Clans Profile Name
      placeholder: Nurulya
    validations:
      required: true
  - type: input
    id: player-tag
    attributes:
      label: Player Tag
      description: >
        Your Clash of Clans Player Tag
      placeholder: "#22G99JQ99"
    validations:
      required: true
  - type: dropdown
    id: account-type
    attributes:
      label: Account Type
      description: >
        Your Clash of Clans Account Type
      options:
        - Main Account
        - Alt Account
    validations:
      required: true
  - type: dropdown
    id: standard-time
    attributes:
      label: Standard Time
      description: >
        Your Time Zone Without Daylight Saving Time
      options:
        - UTC -12:00
        - UTC -11:00
        - UTC -10:00
        - UTC -09:30
        - UTC -09:00
        - UTC -08:00
        - UTC -07:00
        - UTC -06:00
        - UTC -05:00
        - UTC -04:00
        - UTC -03:30
        - UTC -03:00
        - UTC -02:00
        - UTC -01:00
        - UTC ±00:00
        - UTC +01:00
        - UTC +02:00
        - UTC +03:00
        - UTC +03:30
        - UTC +04:00
        - UTC +04:30
        - UTC +05:00
        - UTC +05:30
        - UTC +05:45
        - UTC +06:00
        - UTC +06:30
        - UTC +07:00
        - UTC +08:00
        - UTC +08:45
        - UTC +09:00
        - UTC +09:30
        - UTC +10:00
        - UTC +10:30
        - UTC +11:00
        - UTC +12:00
        - UTC +12:45
        - UTC +13:00
        - UTC +14:00
    validations:
      required: true
  - type: dropdown
    id: discovery
    attributes:
      label: Discovery
      description: >
        The Way You Found Out About Our Clan
      options:
        - Via In-game Recruitment
        - Via Friend Invitation
        - Via Social Media
        - Other
    validations:
      required: true
  - type: input
    id: referrer
    attributes:
      label: Referrer
      description: >
        Player Tag of the Referrer
      placeholder: "#G0GV0J82J"
  - type: markdown
    attributes:
      value: |
        ---
        We will review your request as soon as possible. Thanks!
